# Generated by Django 4.2.6 on 2025-10-14 09:42

from django.db import migrations

# These are the room details from the problem description
ROOMS_TO_CREATE = {
    'PRIVATE': {'count': 8, 'capacity': 1},
    'CONFERENCE': {'count': 4, 'capacity': 10}, # Assuming a default capacity
    'SHARED': {'count': 3, 'capacity': 4},
}

def create_rooms(apps, schema_editor):
    Room = apps.get_model('bookings', 'Room')
    for room_type, details in ROOMS_TO_CREATE.items():
        for i in range(1, details['count'] + 1):
            Room.objects.create(
                name=f"{room_type.capitalize()} {i}",
                room_type=room_type,
                capacity=details['capacity']
            )

def delete_rooms(apps, schema_editor):
    # This function allows us to reverse the migration if needed
    Room = apps.get_model('bookings', 'Room')
    for room_type in ROOMS_TO_CREATE:
        Room.objects.filter(room_type=room_type).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_rooms, reverse_code=delete_rooms),
    ]